spring:
  datasource:
    url: jdbc:mysql://47.111.234.21:3336/zhuluoji?useUnicode=true&characterEncoding=utf8&useCursorFetch=true&autoReconnect=true&failOverReadOnly=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 654321
    hikari:
      max-lifetime: 50000